### ISSUE TITLE
rocker/tidyverse:3.4.3への対応について

### ISSUE THREAD

**Issue by h-hosaka** [ymattu/mecab-d#1]
こんにちは。
こちら、ベースイメージを現在の最新バージョンの
rocker/tidyverse:3.4.3
へ対応する予定はございますでしょうか？

**Comment by ymattu** [comment]
@h-hosaka ご連絡ありがとうございます。放ったらかしにしていました。。。
近日中に対応予定です。
よろしくお願いいたします

**Comment by ymattu** [comment]
@h-hosaka 
先日R3.4.4がリリースされたので今回のアップデートで一気にあげてしまいました。
よろしくお願いします。

http://y-mattu.hatenablog.com/entry/mecabd20180320
